CompanyRegister.App/Controllers/AccountController.cs
using CompanyRegister.App.Infrastructure.Abstract;
using CompanyRegister.Models.View;
using System.Web.Mvc;

namespace CompanyRegister.App.Controllers
{
    public class AccountController : Controller
    {
        private IAuthProvider authProvider;
        public AccountController(IAuthProvider authProvider)
        {
            this.authProvider = authProvider;
        }



        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(LoginViewModel vm, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                if (authProvider.Authenticate(vm.Username, vm.Password))
                {
                    return Redirect(returnUrl ?? Url.Action("All", "Operator"));
                }
                else
                {
                    ModelState.AddModelError("", "Incorect username or password");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
            
    }
}

CompanyRegister.App/Controllers/EmployeeController.cs
using CompanyRegister.Models.Entity;
using CompanyRegister.Repositories.Abstract;
using System.Linq;
using System.Web.Mvc;

namespace CompanyRegister.App.Controllers
{
    public class EmployeeController : Controller
    {
        private IEmployeeRepository repository;
        public EmployeeController(IEmployeeRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public ActionResult All(string name)
        {
            var employees = from e in repository.Employees select e;
            if (!string.IsNullOrEmpty(name))
            {
                foreach (var employee in employees)
                {
                    string fullName = employee.FirstName + " " + employee.LastName;
                    if (fullName.Contains(name))
                    {
                        employees = employees.Where(i => i == employee);
                    }
                }
            }
            return View(employees);
        }
        [HttpPost]
        public ActionResult All(Employee employee)
        {
            return RedirectToAction(employee.FirstName);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var res = repository.Details(id);
            return View(res);
        }

        [HttpGet]
        public ActionResult Search()
        {
            return this.View();
        }

        [HttpPost]
        public ActionResult Search(string name)
        {
            Employee employee = repository.Employees.FirstOrDefault(e => e.FirstName.Contains(name) || e.LastName.Contains(name));
            if (employee != null)
            {
                return View(employee);
            }
            return View(employee);
        }
    }
}

CompanyRegister.App/Controllers/OperatorController.cs
using CompanyRegister.Models.Entity;
using CompanyRegister.Repositories.Abstract;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompanyRegister.App.Controllers
{
    [Authorize]
    public class OperatorController : Controller
    {
        private IEmployeeRepository repository;

        public OperatorController(IEmployeeRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public ActionResult All(string name)
        {

            return View(repository.Employees);
        }


        public ViewResult Edit(int id)
        {
            Employee employee = repository.Employees.FirstOrDefault(em => em.Id == id);
            return View(employee);

        }
        
        [HttpPost]
        public ActionResult Edit(Employee employee, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    employee.ImageMimeType = image.ContentType;
                    employee.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(employee.ImageData, 0, image.ContentLength);
                }

                this.repository.SaveEmployee(employee);
                TempData["message"] = string.Format($"{employee.FirstName} has been saved");
                return RedirectToAction("All");
            }
            else
            {
                return View(employee);
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View("Edit", new Employee());
        }

        public ActionResult Delete(int Id)
        {
            Employee deletedProduct = repository.DeleteEmployee(Id);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format($"{deletedProduct.FirstName} {deletedProduct.LastName} was deleted");
            }
            return RedirectToAction("All");
        }

        public FileContentResult GetImage(int employeeId)
        {
            Employee product = repository.Employees
                .FirstOrDefault(e => e.Id == employeeId);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

CompanyRegister.App/Views/Employee/All.cshtml
@model IEnumerable<CompanyRegister.Models.Entity.Employee>
@{
    ViewBag.Title = "All";
}
<link href="~/Styles/All.css" rel="stylesheet" />
<h2>All Employees</h2>

<form asp-controller="Employee" asp-action="All">
    <div class="form-group">
        <p>
            <input type="text" name="name" class="form-control pull-left" placeholder="Search name...">
            <input type="submit" class="btn btn-success right" value="Search" />
        </p>
    </div>
</form>

<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th>Name</th>
        <th>Info</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.FirstName @item.SecondName @item.LastName</td>
            <td>@Html.ActionLink("Details", "Details", "Employee", new { id = item.Id }, new { @id = "details" })</td>
        </tr>
    }
</table>

CompanyRegister.App/Views/Employee/Details.cshtml
@model CompanyRegister.Models.Entity.Employee
@{
    ViewBag.Title = "Details";
}
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<link href="~/Styles/All.css" rel="stylesheet" />

<div>
    <h3>@Html.DisplayFor(vm => vm.FirstName) @Html.DisplayFor(vm => vm.SecondName) @Html.DisplayFor(vm => vm.LastName)</h3>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateHired)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateHired)
        </dd>
    </dl>
</div>


<p>
    @Html.ActionLink("Back to all", "All", "Employee", new {@id = "details" })
</p>

CompanyRegister.App/Views/Employee/Search.cshtml
@model CompanyRegister.Models.Entity.Employee
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>
<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th>Name</th>
        <th>Info</th>
    </tr>
    <tr>
        <td>@Model.FirstName @Model.SecondName @Model.LastName</td>
        <td>@Html.ActionLink("Details", "Details", "Employee", new { id = Model.Id }, new { @id = "details" })</td>
    </tr>

</table>

CompanyRegister.App/Views/Operator/All.cshtml
@model IEnumerable<CompanyRegister.Models.Entity.Employee>
@{
    ViewBag.Title = "All";
    Layout = "~/Views/Shared/_OperatorLayout.cshtml";
    HtmlHelper.ClientValidationEnabled = true;
    HtmlHelper.UnobtrusiveJavaScriptEnabled = true;
}
<link href="~/Styles/All.css" rel="stylesheet" />
<h2>All Employees</h2>
<div class="panel-footer">
        @Html.ActionLink("Add new employee", "Create", null, new {@class = "btn btn-default" })
</div>
<table class="table table-striped table-condensed table-bordered">
    <tr>
        <th>Name</th>
        <th>Info</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>

    @foreach (var employee in Model)
    {
        <tr>
            <td>@employee.FirstName @employee.SecondName @employee.LastName</td>
            <td>@Html.ActionLink("Details", "Details", "Employee", new { id = employee.Id }, new { @id = "details" })</td>
            <td>@Html.ActionLink("Edit", "Edit", "Operator", new { id = employee.Id }, new { @id = "edit"} )</td>
            <td>
                @using (Html.BeginForm("Delete", "Operator"))
                {
                    @Html.Hidden("Id", employee.Id)
                    <input type="submit" class="btn btn-warning btn-xs" value="Delete" />
                }
            </td>
        </tr>
    }
</table>

CompanyRegister.App/Views/Operator/Edit.cshtml
@model CompanyRegister.Models.Entity.Employee
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_OperatorLayout.cshtml";
}
<link href="~/Styles/All.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<div class="panel">
    <div class="panel-heading">
        <h3>Edit @Model.FirstName</h3>
    </div>
    @using (Html.BeginForm("Edit", "Operator", FormMethod.Post, new { enctpye = "multipart/form-data" }))
    {
        <div class="panel-body">
            @Html.HiddenFor(id => id.Id)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                switch (property.PropertyName)
                {
                    case "Id":
                    case "ImageData":
                    case "ImageMimeType":
                        break;

                    default:
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                            @Html.ValidationMessage(property.PropertyName)
                        </div>
                        break;

                }
            }
        </div>
        
        <div class="form-group">
            <div style="position:relative">
                <label>Image</label>
                <a href='javascript:;' class="btn">
                    Choose file...
                    <input type="file" name="Image" size="40" style="position:absolute;z-index:2;top:0;left:0;
                           filter: alpha(opacity=0);opacity:0;background-color:transparent;color:transparent;"
                           onchange='$("#upload-file-info").html($(this).val())' />
                </a>
                <span class="label label-info" id="upload-file-info"></span>
            </div>
            @if (Model.ImageData == null)
            {
                <div class="form-control-static">No Image</div>
            }
            else
            {
                <img class="img-thumbnail" width="150" height="150" src="@Url.Action("GetImage", "Operator", new { Model.Id })" />
            }
        </div>

        <div class="panel-footer">
            <input type="submit" class="btn btn-primary" value="Save" />
            @Html.ActionLink("Cancel and return to all", "All", "Operator", null, new { @class = "btn btn-default" })
        </div>
    }
    <script src="~/Scripts/ImageUploader.js"></script>
</div>

CompanyRegister.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CompanyRegister.App/Views/Shared/_OperatorLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>